common: &common_settings
  home_title: Home
  guest_name: 손님
  notice: 공지
  previous_label: "&laquo; 이전"
  next_label: "다음 &raquo;"

development: &non_production_settings
  <<: *common_settings
  site_url: http://yoursite.com
  site_name: Yoursite
  admin_email: admin@yoursite.com
  
test:
  <<: *non_production_settings
  
production:
  <<: *common_settings
  site_url: http://yoursite.com
  site_name: Yoursite
  admin_email: admin@yoursite.com
